version: '3'
services:
  app:
    build: .
    image: fuzzdom
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    links:
      - selenium
    volumes:
      - ./fuzzdom:/code/fuzzdom
      - ./tmp:/tmp
      - ./datadir:/code/datadir
      - ./trained_models:/code/trained_models
      - miniwob-volume:/opt/conda/lib/python3.6/site-packages/miniwob
  selenium:
    image: selenium/standalone-chrome
    volumes:
      - miniwob-volume:/opt/conda/lib/python3.6/site-packages/miniwob:ro
    ports:
      - 4444:4444
volumes:
  miniwob-volume:
