version: "3"
services:
  app:
    build: .
    image: fuzzdom
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    links:
      - selenium
      - testsite
    volumes:
      - ./fuzzdom:/code/fuzzdom
      - miniwob-volume:/tmp
      - miniwob-volume:/root/.cache
      - ./datadir:/code/datadir
      - ./trained_models:/code/trained_models
      - miniwob-volume:/opt/conda/lib/python3.7/site-packages/miniwob
  selenium:
    image: selenium/standalone-chrome
    links:
      - testsite
    volumes:
      - miniwob-volume:/opt/conda/lib/python3.7/site-packages/miniwob:ro
      - ./fuzzdom:/code/fuzzom
    ports:
      - 4444:4444
  testsite:
    image: nginx
    volumes:
      - ./fuzzdom/testsite:/usr/share/nginx/html
    ports:
      - 8080:80
volumes:
  miniwob-volume:
