version: "3"
services:
  app:
    build: .
    image: fuzzdom
    # for CUDA access
    ipc: "host"
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
      PROXY_HOST: http://squidproxy:3128/
    links:
      - selenium
      - testsite
      - squidproxy
    volumes:
      - ./fuzzdom:/code/fuzzdom
      - ./tmp:/tmp
      - miniwob-volume:/root/.cache
      - ./datadir:/code/datadir
      - ./trained_models:/code/trained_models
      - miniwob-volume:/opt/conda/lib/python3.7/site-packages/miniwob
  selenium:
    image: selenium/standalone-chrome
    links:
      - testsite
      - squidproxy
    volumes:
      - miniwob-volume:/opt/conda/lib/python3.7/site-packages/miniwob:ro
      - ./fuzzdom:/code/fuzzom
    ports:
      - 4444:4444
  testsite:
    image: nginx
    volumes:
      - ./fuzzdom/testsite:/usr/share/nginx/html
    ports:
      - 8080:80
  squidproxy:
    image: sameersbn/squid:3.5.27-2
    restart: always
    links:
      - testsite
    volumes:
      - /srv/docker/squid/cache:/var/spool/squid
    ports:
      - 3128:3128
volumes:
  miniwob-volume:
